import {
  TokenBTC,
  TokenETH,
  TokenSOL,
  TokenUSDT,
  TokenUSDC,
  TokenBNB,
  TokenXRP,
  TokenADA,
  TokenDOGE,
  TokenTON,
  TokenTRX,
  TokenDOT,
  TokenAVAX,
  TokenLINK,
  TokenMATIC,
  TokenSHIB,
  TokenLTC,
  TokenBCH,
  TokenUNI,
  TokenATOM,
} from "@web3icons/react";

import type { CryptoIconComponent } from "./crypto.types";

export const cryptoIcons: Record<string, CryptoIconComponent> = {
  BTC: TokenBTC,
  ETH: TokenETH,
  SOL: TokenSOL,
  USDT: TokenUSDT,
  USDC: TokenUSDC,
  BNB: TokenBNB,
  XRP: TokenXRP,
  ADA: TokenADA,
  DOGE: TokenDOGE,
  TON: TokenTON,
  TRX: TokenTRX,
  DOT: TokenDOT,
  AVAX: TokenAVAX,
  LINK: TokenLINK,
  MATIC: TokenMATIC,
  SHIB: TokenSHIB,
  LTC: TokenLTC,
  BCH: TokenBCH,
  UNI: TokenUNI,
  ATOM: TokenATOM,
};
